#!/bin/bash

sed -i "s/%WORKER_PROCESSES%/$LB_STATIC_DASHBOARD_NUM/" /nginx.conf
sed -i "s/%WEB_PORT%/$STATIC_DASHBOARD_PORT/" /nginx.conf
sed -i "s/%API_PORT%/$SERVICES_API_PORT/" /nginx.conf

STATIC_SERVERS=''
for i in $(seq 1 $LB_STATIC_DASHBOARD_NUM)
do
  STATIC_SERVERS="$STATIC_SERVERS\nserver ${COMPOSE_PROJECT_NAME}_${LB_STATIC_DASHBOARD_NAME}_$i:${STATIC_DASHBOARD_PORT};"
done
sed -i "s/%STATIC_SERVERS%/$STATIC_SERVERS/" /nginx.conf

SERVICES_SERVERS=''
for i in $(seq 1 $LB_SERVICES_API_NUM)
do
  SERVICES_SERVERS="$SERVICES_SERVERS\nserver ${COMPOSE_PROJECT_NAME}_${LB_SERVICES_API_NAME}_$i:${SERVICES_API_PORT};"
done
sed -i "s/%SERVICES_SERVERS%/$SERVICES_SERVERS/" /nginx.conf
